### ISSUE TITLE
Beyond Compare not being invoked on Windows 10

### ISSUE THREAD

**Issue by rlcranney** [npadley/BeyondCompare#4]
Hi,

I have Beyond Compare version 3.3.13 installed on my PC.  After installing this package, it took me a few mins to determine that [Ctrl-Opt-D] equates to [Ctrl+Alt+D] on Windows... I found it on the Sublime Text Tools menu.  

Unfortunately, however, when I invoke BeyondCompare using either the keystroke or menu item, BeyondCompare does not load.  As far as I know, it's installed in the default space...  I am running SublimeText3 Build 3126.

Do you have any suggestions?

**Comment by npadley** [comment]
Thanks for the feedback. I originally programmed the plugin with Beyond Compare 4 in mind, meaning I hardcoded the path to the file. I need to set up some time to test and fix it for version 3. I will also update the instructions to reflect the proper windows keys to invoke it.

**Comment by npadley** [comment]
Hi @rcranney - I just put in a quick update today to give you a preference file where you can set a custom path to version 3. Let me know if that allows you successfully invoke BeyondCompare within ST now. You should also see it error more gracefully if it can't actually find the program.

**Comment by rlcranney** [comment]
I renamed the BeyondCompare.sublime-package file to BeyondCompare.zip, unzipped it, and updated  the BeyondCompare.sublime-settings file with the below path.  I then replaced the updated file into the zip fil and renamed the zip file back to original name..  I am still getting an error message when I start SublimeText... and suggestions you could offer?
{
    "beyond_compare_path": "C:\Program Files (x86)\Beyond Compare 3\BCompare.exe"
}

**Comment by npadley** [comment]
Ok. Give it another try - just pushed out another quick fix to add the preference file to the actual preferences menu. (I'm still a bit new at this whole thing! You'll need to escape your path, as the backslash is an escaped character in Windows. So use the following:

`{
    "beyond_compare_path": "C:\\Program Files (x86)\\Beyond Compare 3\\BCompare.exe"
}`

**Comment by rlcranney** [comment]
That worked... Thanks for fixing this issue.
