### ISSUE TITLE
Could not find beyond compare error

### ISSUE THREAD

**Issue by Samjin** [npadley/BeyondCompare#5]
I have a path defined as following by default after installed the plugin. 
    "beyond_compare_path": "/usr/local/bin/bcompare"
but it keeps saying "could not find Beyond Compare, Please set the path to your tool in BeyondCompare.sublime-settings."
Any idea how to solve this problem? I am using windows

**Comment by npadley** [comment]
It looks like you have a linux/mac path. You’ll probably want to add the link to the path to the application in windows. The plugin tries to auto-detect the path, but if you have a version older than v4, you’ll need to manually specify the path.

Thanks,
Nick
