### ISSUE TITLE
left pane always shows beyond compare exe 

### ISSUE THREAD

**Issue by cpeng03d** [npadley/BeyondCompare#8]
Hi I seem to have this issue:
On windows I use a portable version of beyond compare (unzipped from a zip file)
and in this plugin setting I set the custom path to point to that beyond compare exe.
When I right click in sublime on "Beyond compare: show diff",
BC does open, but the left pane is always opening the beyond compare exe file instead of the file I want to compare.
The right pane shows the file I clicked from which is fine.

**Comment by npadley** [comment]
Best guess is that you may have the exe improperly in the path. Can you respond with your settings?
